#! /usr/bin/env bash

VARIANT=${1:?Theme variant required}
shift 1

readonly INPUT_DIR=templates
readonly OUTPUT_DIR=themes

if [[ ! -d ${INPUT_DIR} ]]; then
  echo "Input directory '${INPUT_DIR}' does not exist" >&2
  exit 1
fi

if [[ ! -d ${OUTPUT_DIR} ]]; then
  echo "Output directory '${INPUT_DIR}' does not exist" >&2
  exit 1
fi

readonly T_0='00000000'
readonly T_01='04'
readonly T_02='08'
readonly T_03='0A'
readonly T_04='0C'
readonly T_1='20'
readonly T_2='40'
readonly T_3='60'
readonly T_4='80'
readonly T_5='A0'
readonly T_6='C0'
readonly T_7='E0'

case "${VARIANT,,}" in
  ( light | l )
    readonly BG_DIM='EBEBE4'
    readonly BG='F5F5F2'
    readonly FG='5C6A72'
    readonly RED='F85552'
    readonly ORANGE='F57D26'
    readonly YELLOW='D69A00'
    readonly GREEN='8DA101'
    readonly CYAN='35A77C'
    readonly BLUE='3A94C5'
    readonly PURPLE='DF69BA'

    readonly ACCENT=${GREEN}

    readonly BORDER=${FG}${T_4}
    readonly BORDER_COLORED=${ACCENT}${T_4}

    readonly VARIANT=Light
    ;;

  ( dark | d )
    readonly BG_DIM='141617'
    readonly BG='1D2021'
    readonly FG='DDC7A1'
    readonly RED='EA6962'
    readonly ORANGE='E78A4E'
    readonly YELLOW='D8A657'
    readonly GREEN='A9B665'
    readonly CYAN='89B482'
    readonly BLUE='7DAEA3'
    readonly PURPLE='D3869B'

    readonly ACCENT=${YELLOW}

    readonly BORDER=${FG}${T_4}
    readonly BORDER_COLORED=${ACCENT}${T_4}

    readonly VARIANT=Dark
    ;;

  ( * )
    echo "Variant '${VARIANT}' is not supported (choose 'light' / 'l' or 'dark' / 'd')"
    exit 1
    ;;
esac

readonly INPUT_FILE=${INPUT_DIR}/Evergruv-${VARIANT}.tmpl.json
if [[ ! -f ${INPUT_FILE} ]]; then
  echo "Autogenerated input file path '${INPUT_FILE}' invalid (file does not exist)" >&2
  exit 1
fi

readonly OUTPUT_FILE=${OUTPUT_DIR}/Evergruv-${VARIANT}.json

echo 'Generating theme'
echo "  -> variant: ${VARIANT}"
echo "  -> input:   ${INPUT_FILE}"
echo "  -> output:  ${OUTPUT_FILE}"

# shellcheck disable=SC2016
sed \
  --expression "s|{{VARIANT}}|${VARIANT,,}|g"             \
  --expression "s|{{T_0}}|${T_0}|g"                       \
  --expression "s|{{T_01}}|${T_01}|g"                     \
  --expression "s|{{T_02}}|${T_02}|g"                     \
  --expression "s|{{T_03}}|${T_03}|g"                     \
  --expression "s|{{T_04}}|${T_04}|g"                     \
  --expression "s|{{T_1}}|${T_1}|g"                       \
  --expression "s|{{T_2}}|${T_2}|g"                       \
  --expression "s|{{T_3}}|${T_3}|g"                       \
  --expression "s|{{T_4}}|${T_4}|g"                       \
  --expression "s|{{T_5}}|${T_5}|g"                       \
  --expression "s|{{T_6}}|${T_6}|g"                       \
  --expression "s|{{T_7}}|${T_7}|g"                       \
  --expression "s|{{BG_DIM}}|${BG_DIM}|g" \
  --expression "s|{{BG}}|${BG}|g"         \
  --expression "s|{{FG}}|${FG}|g"         \
  --expression "s|{{RED}}|${RED}|g"                       \
  --expression "s|{{ORANGE}}|${ORANGE}|g"                 \
  --expression "s|{{YELLOW}}|${YELLOW}|g"                 \
  --expression "s|{{GREEN}}|${GREEN}|g"                   \
  --expression "s|{{CYAN}}|${CYAN}|g"                     \
  --expression "s|{{BLUE}}|${BLUE}|g"                     \
  --expression "s|{{PURPLE}}|${PURPLE}|g"                 \
  --expression "s|{{ACCENT}}|${ACCENT}|g"                 \
  --expression "s|{{BORDER}}|${BORDER}|g"                 \
  --expression "s|{{BORDER_COLORED}}|${BORDER_COLORED}|g" \
  "${INPUT_FILE}" >"${OUTPUT_FILE}"
